default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  pool: 5
  host: localhost

development:
  <<: *default
  database: stopwatch_development

test:
  <<: *default
  database: stopwatch_test

staging:
  <<: *default
  database: stopwatch_staging

production:
  <<: *default
  database: stopwatch_production
